Repository PERHAPS-4IW3/Perhaps, pull requests merged in 2019-02, with the labels that each got.

#11 Develop
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a.xml
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/workspace.xml
  App/.env
  App/composer.json
  App/composer.lock
  App/src/Controller/Back/ProjetController.php
  App/src/Controller/Front/HomeController.php
  App/src/Controller/Front/ProjetController.php
  App/src/DataFixtures/ProjetFixtures.php
  App/src/Entity/Categorie.php
  App/src/Entity/Competence.php
  App/src/Entity/Devis.php
  App/src/Entity/Facture.php
  App/src/Entity/Freelancer.php
  App/src/Entity/Projet.php
  App/src/Entity/TypeProjet.php
  App/src/Form/ProjetType.php
  App/src/Repository/ProjetRepository.php
  App/symfony.lock
  App/templates/Back/Projet/edit.html.twig
  App/templates/Back/Projet/index.html.twig
  App/templates/Front/Home/home.html.twig
  App/templates/Front/Projet/index.html.twig
  App/templates/Front/Projet/show.html.twig
  App/templates/base.html.twig
Labels: Configuration, enhancement

#13 Develop
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a.xml
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/workspace.xml
  App/config/packages/security.yaml
  App/config/packages/twig.yaml
  App/config/routes/annotations.yaml
  App/config/services.yaml
  App/src/Controller/Back/ProjetController.php
  App/src/Controller/Front/SecurityController.php
  App/src/DataFixtures/ProjetFixtures.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/Freelancer.php
  App/src/Entity/Projet.php
  App/src/Entity/TypeProjet.php
  App/src/Entity/User.php
  App/src/Form/ProjetType.php
  App/src/Form/UserType.php
  App/src/Repository/UserRepository.php
  App/templates/Back/Projet/edit.html.twig
  App/templates/Back/Projet/index.html.twig
  App/templates/Back/Projet/new.html.twig
  App/templates/Front/Projet/show.html.twig
  App/templates/Front/Security/login.html.twig
  App/templates/Front/Security/register.html.twig
  App/templates/base.html.twig
Labels: Configuration, enhancement

#15 Fix User + menu
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a.xml
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/workspace.xml
  App/config/packages/security.yaml
  App/src/DataFixtures/ProjetFixtures.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/templates/Back/Projet/new.html.twig
  App/templates/Front/Security/login.html.twig
  App/templates/Front/Security/register.html.twig
  App/templates/base.html.twig
Labels: Configuration, bug

#16 gitingnore / .Idea Del
  .idea/Perhaps.iml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/dataSources/11bb59a2-7da8-429c-b96f-2be79e555f9f.xml
  .idea/dataSources/11bb59a2-7da8-429c-b96f-2be79e555f9f/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/11bb59a2-7da8-429c-b96f-2be79e555f9f/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a.xml
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/misc.xml
  .idea/modules.xml
  .idea/php.xml
  .idea/vcs.xml
  .idea/workspace.xml
  App/.env
  App/.gitignore
Labels: Configuration, bug

#38 add a footer and link => contact form
  App/.env
  App/composer.json
  App/composer.lock
  App/src/Controller/ContactController.php
  App/src/Form/ContactType.php
  App/templates/base.html.twig
  App/templates/contact.html.twig
Labels: Configuration, enhancement

#39 Gestion des profils + page accueil + fix webpack
  App/assets/css/app.css
  App/assets/js/app.js
  App/config/packages/security.yaml
  App/package-lock.json
  App/package.json
  App/public/images/ESGI.jpg
  App/public/images/PERHAPS.png
  App/public/images/PERHAPS2.png
  App/public/images/logo.png
  App/src/Controller/Admin/UserController.php
  App/src/Controller/Back/UserController.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/src/Form/User1Type.php
  App/templates/Admin/user/_delete_form.html.twig
  App/templates/Admin/user/_form.html.twig
  App/templates/Admin/user/edit.html.twig
  App/templates/Admin/user/index.html.twig
  App/templates/Admin/user/new.html.twig
  App/templates/Admin/user/show.html.twig
  App/templates/Back/user/_delete_form.html.twig
  App/templates/Back/user/_form.html.twig
  App/templates/Back/user/edit.html.twig
  App/templates/Back/user/index.html.twig
  App/templates/Back/user/show.html.twig
  App/templates/Front/Home/home.html.twig
  App/templates/base.html.twig
  App/yarn.lock
Labels: Configuration, bug, enhancement, evolution

#42 Footer + Font awesome
  .idea/Perhaps.iml
  .idea/dataSources.local.xml
  .idea/dataSources.xml
  .idea/dataSources/11bb59a2-7da8-429c-b96f-2be79e555f9f/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/11bb59a2-7da8-429c-b96f-2be79e555f9f/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/95734d26-8c66-40e0-9204-0c96117c4b7a/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/dataSources/cb9bb8ce-0cd4-413d-9b8a-8073af3bfc11/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/cb9bb8ce-0cd4-413d-9b8a-8073af3bfc11/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/dataSources/fc354b6c-5bd4-4092-aa2a-da2231268d4a.xml
  .idea/dataSources/fc354b6c-5bd4-4092-aa2a-da2231268d4a/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/fc354b6c-5bd4-4092-aa2a-da2231268d4a/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/misc.xml
  .idea/modules.xml
  .idea/php.xml
  .idea/vcs.xml
  .idea/workspace.xml
  App/.env
  App/assets/css/app.css
  App/public/images/freelancer.png
  App/public/images/trophy.svg
  App/templates/Front/Home/home.html.twig
  App/templates/base.html.twig
  App/templates/contact.html.twig
  App/yarn.lock
Labels: enhancement, evolution

#43 Footer + dropdown menu
  .idea/dataSources/b8126456-dd23-463c-bbf9-fb696b1f71fc.xml
  .idea/dataSources/b8126456-dd23-463c-bbf9-fb696b1f71fc/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/workspace.xml
  App/.env
  App/assets/css/app.css
  App/package.json
  App/src/DataFixtures/ProjetFixtures.php
  App/templates/base.html.twig
  App/yarn.lock
Labels: evolution

#44 Freelancer add
  App/.env
  App/assets/css/app.css
  App/public/images/user.svg
  App/src/Controller/Back/UserController.php
  App/src/Form/User1Type.php
  App/templates/Front/Projet/index.html.twig
  App/templates/Front/freelancer/ShowFree.html.twig
  App/templates/base.html.twig
Labels: enhancement, evolution

#45 Fixes Modif mdp + reset with token
  App/src/Controller/Front/SecurityController.php
  App/src/Entity/User.php
  App/templates/Front/Home/home.html.twig
  App/templates/Front/Security/resetPassword.html.twig
  App/templates/base.html.twig
Labels: bug

#46 Inscription
  .idea/dataSources/b8126456-dd23-463c-bbf9-fb696b1f71fc.xml
  .idea/dataSources/b8126456-dd23-463c-bbf9-fb696b1f71fc/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  App/.env
  App/assets/css/app.css
  App/src/Controller/Front/SecurityController.php
  App/src/Entity/Freelancer.php
  App/src/Entity/User.php
  App/src/Form/UserType.php
  App/templates/Front/Security/register.html.twig
  App/templates/base.html.twig
Labels: Configuration, bug, enhancement, evolution

#47 Develop
  .idea/dataSources.local.xml
  .idea/dataSources/159693d6-ee62-4803-83fd-bca6700d4d3e/storage_v2/_src_/database/perhaps.WZuK1w.meta
  .idea/dataSources/159693d6-ee62-4803-83fd-bca6700d4d3e/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  .idea/dataSources/159693d6-ee62-4803-83fd-bca6700d4d3e/storage_v2/_src_/database/postgres.edMnLQ.meta
  .idea/dataSources/159693d6-ee62-4803-83fd-bca6700d4d3e/storage_v2/_src_/database/postgres.edMnLQ/schema/public.abK9xQ.meta
  .idea/misc.xml
  .idea/workspace.xml
  App/src/Controller/Front/ContactController.php
  App/src/Controller/Front/FreelancerController.php
  App/src/Controller/Front/ProjetController.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/src/Form/FreelancerSearchType.php
  App/src/Form/FreelancerType.php
  App/src/Form/ProjetSearchType.php
  App/src/Repository/ProjetRepository.php
  App/src/Repository/UserRepository.php
  App/templates/Front/Projet/index.html.twig
  App/templates/Front/freelancer/index.html.twig
Labels: Configuration, enhancement

#48 Modification design + fix dropdown + fixgestion de profil
  App/assets/css/app.css
  App/assets/js/app.js
  App/public/images/slide3.jpg
  App/public/images/slider1.jpg
  App/public/images/slider2.jpg
  App/src/Controller/Back/UserController.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Form/ChangePasswordType.php
  App/templates/Back/user/changePass.html.twig
  App/templates/Back/user/edit.html.twig
  App/templates/Back/user/index.html.twig
  App/templates/Back/user/show.html.twig
  App/templates/Front/Home/home.html.twig
  App/templates/Front/Projet/index.html.twig
  App/templates/Front/freelancer/ShowFree.html.twig
  App/templates/base.html.twig
Labels: Configuration, bug, enhancement, evolution

#55 Fin Inscription Fixes #24 + correction
  App/assets/css/app.css
  App/assets/js/app.js
  App/src/Controller/Back/FreelancerController.php
  App/src/Controller/Back/UserController.php
  App/src/Controller/Front/ContactController.php
  App/src/Controller/Front/FreelancerController.php
  App/src/Controller/Front/ProjetController.php
  App/src/Controller/Front/SecurityController.php
  App/src/DataFixtures/AppFixtures.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/src/Form/ProjetSearchType.php
  App/src/Form/UserType.php
  App/templates/Front/Security/register.html.twig
  App/templates/Front/Security/resetPassword.html.twig
  App/templates/base.html.twig
  App/templates/contact.html.twig
Labels: Configuration, bug, enhancement, evolution

#49 Pagination Page Projet
  .idea/dataSources.local.xml
  .idea/dataSources/b8126456-dd23-463c-bbf9-fb696b1f71fc.xml
  .idea/dataSources/b8126456-dd23-463c-bbf9-fb696b1f71fc/storage_v2/_src_/database/perhaps.WZuK1w/schema/public.abK9xQ.meta
  App/.env
  App/src/Controller/Back/UserController.php
  App/src/Controller/Front/FreelancerController.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/src/Repository/UserRepository.php
Labels: enhancement, evolution

#57 Profil Corrections
  App/.env
  App/assets/css/app.css
  App/assets/js/app.js
  App/src/Controller/Back/UserController.php
  App/src/DataFixtures/ProjetFixtures.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/src/Repository/ProjetRepository.php
  App/templates/Back/user/_delete_form.html.twig
  App/templates/Back/user/edit.html.twig
  App/templates/Back/user/index.html.twig
  App/templates/Back/user/show.html.twig
  App/templates/Front/Home/home.html.twig
Labels: Configuration, bug, enhancement

#61 Image de profil
  App/.gitignore
  App/assets/css/app.css
  App/composer.json
  App/composer.lock
  App/config/bundles.php
  App/config/packages/liip_imagine.yaml
  App/config/packages/vich_uploader.yaml
  App/config/routes/liip_imagine.yaml
  App/phpunit.xml.dist
  App/public/images/userimg/5c6fd082aa8f7033093982.png
  App/public/images/userimg/user.svg
  App/src/Controller/Back/PayementController.php
  App/src/Controller/Back/ProjetController.php
  App/src/Controller/Back/UserController.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/User.php
  App/src/Form/User1Type.php
  App/src/Migrations/Version20190221122924.php
  App/symfony.lock
  App/templates/Back/Payement/stripe.html.twig
  App/templates/Back/user/index.html.twig
  App/templates/Front/freelancer/ShowFree.html.twig
  App/tests/FuncTest.php
  App/tests/UtilTest.php
Labels: Configuration, enhancement, evolution

#60 Search Freelancer
  App/src/Controller/Front/FreelancerController.php
  App/src/Form/FreelancerSearchType.php
  App/src/Repository/UserRepository.php
  App/templates/Front/freelancer/ShowFree.html.twig
Labels: bug, enhancement, question

#64 Fix functions
  App/.env
  App/assets/css/app.css
  App/composer.lock
  App/src/Controller/Back/ProjetController.php
  App/src/Controller/Front/FreelancerController.php
  App/src/Controller/Front/UserChecker.php
  App/src/DataFixtures/CompetenceFixtures.php
  App/src/DataFixtures/CompetencePossederFixture.php
  App/src/DataFixtures/CompetenceProjetFixture.php
  App/src/DataFixtures/DevisFixture.php
  App/src/DataFixtures/EquipeFixture.php
  App/src/DataFixtures/FactureFixtures.php
  App/src/DataFixtures/NoteFixture.php
  App/src/DataFixtures/ParticipeFixture.php
  App/src/DataFixtures/UserFixtures.php
  App/src/Entity/CompetencePosseder.php
  App/src/Entity/CompetenceProjet.php
  App/src/Entity/Equipe.php
  App/src/Entity/Facture.php
  App/src/Entity/NoteEtCommentaire.php
  App/src/Entity/Participe.php
  App/src/Entity/User.php
  App/templates/Front/freelancer/ShowFree.html.twig
  App/templates/Front/freelancer/index.html.twig
Labels: bug

#66 commit correction inscription
  .idea/phing.xml
  .idea/phpRuntime.xml
  App/assets/js/app.js
  App/src/Controller/Front/Front/SecurityController.php
  App/src/Form/UserType.php
Labels: evolution

#73 Repatcha + CKeditor (editeur de texte )
  App/.env
  App/composer.json
  App/composer.lock
  App/config/bundles.php
  App/config/packages/ewz_recaptcha.yaml
  App/config/packages/fos_ckeditor.yaml
  App/config/packages/google_recaptcha.yaml
  App/config/services.yaml
  App/src/Controller/Front/Front/ContactController.php
  App/src/Form/ContactType.php
  App/symfony.lock
  App/templates/Front/Contact/contact.html.twig
Labels: Configuration, enhancement, evolution

#74 Fix Image Freelancer
  App/public/images/userimg/5c75436f1b59c_cdc.png
  App/src/Form/User1Type.php
  App/templates/Front/freelancer/show.html.twig
Labels: bug, evolution

#76 Postuler Projet + fix des fonctions + datePicker
  App/assets/css/app.css
  App/assets/js/app.js
  App/config/packages/security.yaml
  App/public/images/slider1.png
  App/public/images/userimg/5c7833420b2eb_humour limite.jpg
  App/src/Controller/Back/UserController.php
  App/src/Controller/Front/Back/DevisController.php
  App/src/Controller/Front/Back/ProjetController.php
  App/src/Controller/Front/Back/UserController.php
  App/src/Controller/Front/Front/FreelancerController.php
  App/src/Controller/Front/Front/ProjetController.php
  App/src/DataFixtures/DevisFixture.php
  App/src/Entity/Devis.php
  App/src/Form/ChangePasswordType.php
  App/src/Form/PostulerProjetType.php
  App/src/Form/ProjetSearchType.php
  App/src/Form/ProjetType.php
  App/src/Form/UserModInfoType.php
  App/src/Repository/ProjetRepository.php
  App/src/Repository/UserRepository.php
  App/templates/Back/Projet/index.html.twig
  App/templates/Back/Projet/new.html.twig
  App/templates/Back/user/changePass.html.twig
  App/templates/Back/user/edit.html.twig
  App/templates/Back/user/index.html.twig
  App/templates/Front/Devis/postuler.html.twig
  App/templates/Front/Front/Home/home.html.twig
  App/templates/Front/Projet/show.html.twig
  App/templates/base.html.twig
Labels: bug, enhancement, evolution

#75 Affichage des devis/Freelancer dans projet
  App/.env
  App/assets/css/app.css
  App/src/Controller/Front/Front/ProjetController.php
  App/src/Repository/DevisRepository.php
  App/templates/Front/Projet/show.html.twig
Labels: enhancement, evolution
