Repository PERHAPS-4IW3/Perhaps, pull requests merged in 2019-05, with the labels that each got.

#89 Design, Search and Offers
  App/assets/css/app.css
  App/assets/js/app.js
  App/config/packages/vich_uploader.yaml
  App/config/services.yaml
  App/public/web/cv/5cc4662e7b713_4IWEB.PDF
  App/src/Controller/Front/Back/ProjetController.php
  App/src/Controller/Front/Front/FreelancerController.php
  App/src/Controller/Front/Front/ProjetController.php
  App/src/Controller/Front/Front/SecurityController.php
  App/src/Entity/Projet.php
  App/src/Entity/ProjetSearch.php
  App/src/Entity/User.php
  App/src/Entity/UserSearch.php
  App/src/Form/FreelancerSearchType.php
  App/src/Form/ProjetSearchType.php
  App/src/Form/UserModInfoType.php
  App/src/Form/UserType.php
  App/src/Listener/ImageCacheSubscriber.php
  App/src/Repository/ProjetRepository.php
  App/src/Repository/UserRepository.php
  App/templates/Back/Projet/Offers/showOffers.html.twig
  App/templates/Back/Projet/index.html.twig
  App/templates/Back/user/index.html.twig
  App/templates/Front/Projet/index.html.twig
  App/templates/Front/Projet/show.html.twig
  App/templates/Front/Security/register.html.twig
  App/templates/Front/freelancer/index.html.twig
  App/templates/Front/freelancer/show.html.twig
Labels: Configuration, High, enhancement, evolution

#90 Fix: Search Freelancer
  App/.env
  App/composer.lock
  App/src/Controller/Front/Back/DevisController.php
  App/src/Repository/UserRepository.php
  App/symfony.lock
  App/templates/Front/freelancer/show.html.twig
Labels: bug

#93 message plat
  App/.env
  App/src/Controller/Front/Back/MessageController.php
  App/src/Entity/Message.php
  App/src/Entity/User.php
  App/src/Form/MessageType.php
  App/src/Repository/MessageRepository.php
  App/templates/Back/message/edit.html.twig
  App/templates/Back/message/index.html.twig
  App/templates/Back/message/new.html.twig
  App/yarn.lock
Labels: enhancement, evolution

#94 Ajout freelancer pro
  .idea/dataSources/98ffbb6a-4e80-49c9-93e9-5e890c6ec1e3.xml
  App/assets/css/app.css
  App/assets/js/app.js
  App/composer.lock
  App/src/Controller/Front/Back/ProjetController.php
  App/src/Controller/Front/Front/ProjetController.php
  App/src/DataFixtures/DevisFixture.php
  App/src/DataFixtures/TypeProjetFixtures.php
  App/templates/Back/Projet/Manage/index.html.twig
  App/templates/Back/Projet/Offers/showOffers.html.twig
  App/templates/Back/Projet/new.html.twig
  App/templates/modals/modal_base.html.twig
Labels: evolution
